AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Complens.ai - OAuth App Audit
  Multi-tenant platform to audit third-party OAuth apps in Microsoft 365.

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        TABLE_NAME: !Ref DataTable

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  MicrosoftClientId:
    Type: String
    Default: ''
    Description: Microsoft Entra App Client ID (for validating connections)

  MicrosoftClientSecretArn:
    Type: String
    Default: ''
    Description: ARN of secret containing Microsoft client secret

Resources:
  #############################################
  # Cognito (must be defined before HttpApi)
  #############################################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'complens-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub 'complens-web-${Environment}'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !If [IsProd, 'https://app.complens.ai/callback', 'http://localhost:3000/callback']
      LogoutURLs:
        - !If [IsProd, 'https://app.complens.ai', 'http://localhost:3000']
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'complens-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  #############################################
  # API Gateway HTTP API
  #############################################
  HttpApi:
    Type: AWS::Serverless::HttpApi
    DependsOn:
      - UserPool
      - UserPoolClient
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - !If [IsProd, 'https://app.complens.ai', 'http://localhost:3000']
          - !If [IsProd, !Ref 'AWS::NoValue', 'http://localhost:5173']
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            AuthorizationScopes:
              - openid
              - email
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
              audience:
                - !Ref UserPoolClient

  #############################################
  # Lambda Functions
  #############################################

  # Health check - no auth required
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/health/
      Handler: index.handler
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

  # Get current user info and their organizations
  MeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/me/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
      Events:
        GetMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /me
            Method: GET

  # Organization management
  OrganizationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/organizations/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
      Events:
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations
            Method: GET
        Create:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations
            Method: POST
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}
            Method: GET
        Update:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}
            Method: PUT

  # Members management (within an org)
  MembersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/members/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
      Events:
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/members
            Method: GET
        Add:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/members
            Method: POST
        Update:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/members/{userId}
            Method: PUT
        Remove:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/members/{userId}
            Method: DELETE

  # Properties management (business units within an org)
  PropertiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/properties/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
      Events:
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties
            Method: GET
        Create:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties
            Method: POST
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}
            Method: GET
        Update:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}
            Method: PUT
        Delete:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}
            Method: DELETE

  # Connections management (Microsoft tenants linked to a property)
  ConnectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/connections/
      Handler: index.handler
      Timeout: 60
      Environment:
        Variables:
          MICROSOFT_CLIENT_ID: !Ref MicrosoftClientId
          MICROSOFT_CLIENT_SECRET_ARN: !Ref MicrosoftClientSecretArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MicrosoftClientSecretArn
      Events:
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections
            Method: GET
        Create:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections
            Method: POST
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections/{connId}
            Method: GET
        Delete:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections/{connId}
            Method: DELETE

  # OAuth Apps - scan and list apps for a connection
  AppsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/apps/
      Handler: index.handler
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          MICROSOFT_CLIENT_ID: !Ref MicrosoftClientId
          MICROSOFT_CLIENT_SECRET_ARN: !Ref MicrosoftClientSecretArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MicrosoftClientSecretArn
      Events:
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections/{connId}/apps
            Method: GET
        Scan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /organizations/{orgId}/properties/{propId}/connections/{connId}/scan
            Method: POST

  #############################################
  # DynamoDB
  #############################################
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'complens-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  #############################################
  # S3 + CloudFront (Frontend)
  #############################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'complens-frontend-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'complens-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  FrontendUrl:
    Description: CloudFront URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'

  FrontendBucket:
    Description: S3 bucket for frontend deployment
    Value: !Ref FrontendBucket

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito Domain
    Value: !Sub 'https://complens-${Environment}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'
