AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Complens.ai - Consumer Privacy Scanner

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

  AppName:
    Type: String
    Default: complens

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        TABLE_NAME: !Ref DataTable
        USER_POOL_ID: !Ref UserPool
        USER_POOL_CLIENT_ID: !Ref UserPoolClient

Resources:
  # ============================================
  # COGNITO - Authentication
  # ============================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AppName}-${Environment}-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AppName}-${Environment}-web
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !If
          - IsProd
          - https://app.complens.ai/callback
          - http://localhost:3000/callback
      LogoutURLs:
        - !If
          - IsProd
          - https://app.complens.ai
          - http://localhost:3000
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AppName}-${Environment}-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  # ============================================
  # DYNAMODB - Data Storage
  # ============================================
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ============================================
  # API GATEWAY - HTTP API
  # ============================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - !If [IsProd, "https://app.complens.ai", "http://localhost:3000"]
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            AuthorizationScopes:
              - email
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
                - !Ref UserPoolClient

  # ============================================
  # LAMBDA - API Handler
  # ============================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-${Environment}-api
      Handler: index.handler
      CodeUri: backend/src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        # Public endpoints (no auth)
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

        # Protected endpoints
        GetMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /me
            Method: GET

        UpdateMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /me
            Method: PUT

        # Connected accounts
        GetAccounts:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: GET

        CreateAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: POST

        DeleteAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts/{accountId}
            Method: DELETE

        # Discovered apps
        GetApps:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /apps
            Method: GET

        # Scans
        StartScan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /scan
            Method: POST

        GetScanStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /scan/{scanId}
            Method: GET

        # AI Chat
        Chat:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /chat
            Method: POST

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito hosted UI domain
    Value: !Sub https://${AppName}-${Environment}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com

  TableName:
    Description: DynamoDB table name
    Value: !Ref DataTable
