AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Complens.ai - Consumer Privacy Scanner

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

  AppName:
    Type: String
    Default: complens

  DomainName:
    Type: String
    Default: complens.ai

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for complens.ai

  # Social Identity Providers (optional - leave empty to skip)
  GoogleClientId:
    Type: String
    Default: ""
    Description: Google OAuth Client ID

  GoogleClientSecret:
    Type: String
    Default: ""
    NoEcho: true
    Description: Google OAuth Client Secret

  FacebookAppId:
    Type: String
    Default: ""
    Description: Facebook App ID

  FacebookAppSecret:
    Type: String
    Default: ""
    NoEcho: true
    Description: Facebook App Secret

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        TABLE_NAME: !Ref DataTable
        USER_POOL_ID: !Ref UserPool
        USER_POOL_CLIENT_ID: !Ref UserPoolClient

Conditions:
  IsProd: !Equals [!Ref Environment, prod]
  HasGoogle: !Not [!Equals [!Ref GoogleClientId, ""]]
  HasFacebook: !Not [!Equals [!Ref FacebookAppId, ""]]

Resources:
  # ============================================
  # ACM CERTIFICATE (must be us-east-1 for CloudFront)
  # ============================================
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [IsProd, !Sub "app.${DomainName}", !Sub "dev.${DomainName}"]
      SubjectAlternativeNames:
        - !If [IsProd, !Sub "api.${DomainName}", !Sub "api-dev.${DomainName}"]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !If [IsProd, !Sub "app.${DomainName}", !Sub "dev.${DomainName}"]
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !If [IsProd, !Sub "api.${DomainName}", !Sub "api-dev.${DomainName}"]
          HostedZoneId: !Ref HostedZoneId

  # ============================================
  # S3 BUCKET - Frontend Hosting
  # ============================================
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-${Environment}-frontend-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  # ============================================
  # CLOUDFRONT - CDN
  # ============================================
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AppName}-${Environment}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !If [IsProd, !Sub "app.${DomainName}", !Sub "dev.${DomainName}"]
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # CORS-S3Origin
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

  # ============================================
  # ROUTE53 - DNS
  # ============================================
  FrontendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If [IsProd, !Sub "app.${DomainName}", !Sub "dev.${DomainName}"]
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)

  ApiDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If [IsProd, !Sub "api.${DomainName}", !Sub "api-dev.${DomainName}"]
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId

  # ============================================
  # API GATEWAY CUSTOM DOMAIN
  # ============================================
  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !If [IsProd, !Sub "api.${DomainName}", !Sub "api-dev.${DomainName}"]
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref Certificate

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref ApiDomainName
      Stage: !Ref Environment

  # ============================================
  # COGNITO - Authentication
  # ============================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AppName}-${Environment}-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  # Google Identity Provider
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogle
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: email profile openid
      AttributeMapping:
        email: email
        name: name
        picture: picture

  # Facebook Identity Provider
  FacebookIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasFacebook
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Facebook
      ProviderType: Facebook
      ProviderDetails:
        client_id: !Ref FacebookAppId
        client_secret: !Ref FacebookAppSecret
        authorize_scopes: email public_profile
      AttributeMapping:
        email: email
        name: name

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AppName}-${Environment}-web
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
        - !If [HasGoogle, Google, !Ref "AWS::NoValue"]
        - !If [HasFacebook, Facebook, !Ref "AWS::NoValue"]
      CallbackURLs:
        - !If [IsProd, !Sub "https://app.${DomainName}/", !Sub "https://dev.${DomainName}/"]
        - http://localhost:3000/
      LogoutURLs:
        - !If [IsProd, !Sub "https://app.${DomainName}/", !Sub "https://dev.${DomainName}/"]
        - http://localhost:3000/
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AppName}-${Environment}-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  # ============================================
  # DYNAMODB - Data Storage
  # ============================================
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ============================================
  # API GATEWAY - HTTP API
  # ============================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - !If [IsProd, !Sub "https://app.${DomainName}", !Sub "https://dev.${DomainName}"]
          - http://localhost:3000
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            AuthorizationScopes:
              - email
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
                - !Ref UserPoolClient

  # ============================================
  # LAMBDA - API Handler
  # ============================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-${Environment}-api
      Handler: index.handler
      CodeUri: backend/src/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE
        GetMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /me
            Method: GET
        UpdateMe:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /me
            Method: PUT
        GetAccounts:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: GET
        CreateAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: POST
        DeleteAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts/{accountId}
            Method: DELETE
        GetApps:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /apps
            Method: GET
        StartScan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /scan
            Method: POST
        GetScanStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /scan/{scanId}
            Method: GET
        Chat:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /chat
            Method: POST

Outputs:
  FrontendUrl:
    Description: Frontend URL
    Value: !If [IsProd, !Sub "https://app.${DomainName}", !Sub "https://dev.${DomainName}"]

  ApiUrl:
    Description: API URL
    Value: !If [IsProd, !Sub "https://api.${DomainName}", !Sub "https://api-dev.${DomainName}"]

  FrontendBucket:
    Description: S3 bucket for frontend deployment
    Value: !Ref FrontendBucket

  CloudFrontDistributionId:
    Description: CloudFront distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito hosted UI domain
    Value: !Sub https://${AppName}-${Environment}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com

  TableName:
    Description: DynamoDB table name
    Value: !Ref DataTable
